TRUNCATE TABLE profiles RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE email_verification RESTART IDENTITY;
ALTER SEQUENCE email_verification_id_seq RESTART WITH 1;
TRUNCATE TABLE ads RESTART IDENTITY;
ALTER SEQUENCE ads_id_seq RESTART WITH 1;
TRUNCATE TABLE ads_photo RESTART IDENTITY;
ALTER SEQUENCE ads_photo_id_seq RESTART WITH 1;